version: '3.8'

# Docker Compose configuration for testing environment
# Usage: docker-compose -f docker-compose.yml -f docker-compose.test.yml up

services:
  # Test Database - Separate from development database
  mysql-test:
    image: mysql:8.0
    container_name: talent2income_mysql_test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: talent2income_test
      MYSQL_USER: talent2income_test_user
      MYSQL_PASSWORD: talent2income_test_password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - talent2income_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest_root_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Test Redis - Separate instance for testing
  redis-test:
    image: redis:7-alpine
    container_name: talent2income_redis_test
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    command: redis-server --save "" --appendonly no  # No persistence for tests
    networks:
      - talent2income_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Test Runner Service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: talent2income_test_runner
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./tests/coverage:/var/www/html/tests/coverage
    environment:
      - APP_ENV=testing
      - APP_DEBUG=true
      - APP_KEY=base64:MxNkeg3zg2JuE/y/pp0dx3zo6iXIPxlLQYWdhvGrqgY=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-test
      - DB_PORT=3307
      - DB_DATABASE=talent2income_test
      - DB_USERNAME=talent2income_test_user
      - DB_PASSWORD=talent2income_test_password
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
      - CACHE_STORE=redis
      - SESSION_DRIVER=array
      - QUEUE_CONNECTION=sync
      - MAIL_MAILER=array
      - BROADCAST_DRIVER=null
      - SCOUT_DRIVER=null
    depends_on:
      mysql-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    networks:
      - talent2income_network
    profiles:
      - testing

  # Performance Test Runner
  performance-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: talent2income_performance_test
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./tests/performance-results:/var/www/html/tests/performance-results
    environment:
      - APP_ENV=testing
      - APP_DEBUG=false
      - APP_KEY=base64:MxNkeg3zg2JuE/y/pp0dx3zo6iXIPxlLQYWdhvGrqgY=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - DB_DATABASE=talent2income_test
      - DB_USERNAME=talent2income_test_user
      - DB_PASSWORD=talent2income_test_password
      - REDIS_HOST=redis-test
      - REDIS_PORT=6379
    depends_on:
      mysql-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    networks:
      - talent2income_network
    profiles:
      - performance

  # Security Test Runner
  security-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: talent2income_security_test
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./tests/security-results:/var/www/html/tests/security-results
    environment:
      - APP_ENV=testing
      - APP_DEBUG=false
      - APP_KEY=base64:MxNkeg3zg2JuE/y/pp0dx3zo6iXIPxlLQYWdhvGrqgY=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - DB_DATABASE=talent2income_test
      - DB_USERNAME=talent2income_test_user
      - DB_PASSWORD=talent2income_test_password
    depends_on:
      mysql-test:
        condition: service_healthy
    networks:
      - talent2income_network
    profiles:
      - security

volumes:
  mysql_test_data:
    driver: local
  redis_test_data:
    driver: local

networks:
  talent2income_network:
    external: true